# This is a basic workflow to help you get started with Actions

name: Documentation

# Controls when the action will run.
on:
  workflow_dispatch: {}
  push:
    branches:
      - master
    paths:
      - .github/workflows/Documentation.yaml
      - ADPhotoKit/Classes/**.swift

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" -y
      - name: Install swift-doc
        run: |
          brew install swiftdocorg/formulae/swift-doc
      - name: Generate Documentation
        run: |
          swift doc generate ADPhotoKit/Classes --module-name ADPhotoKit --output Wiki
      - name: Upload Documentation to Wiki
        uses: SwiftDocOrg/github-wiki-publish-action@v1
        with:
          path: "Wiki"
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          
      - name: Generate Documentation
        run: |
          swift doc generate ADPhotoKit/Classes \
          --module-name ADPhotoKit \
          --output Documentation \
          --format html \
          --base-url https://duzexu.github.io/ADPhotoKit/
          
      - name: Permissions
        run: sudo chown -R $USER:$USER /home/runner/work/
 
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          publish_dir: Documentation
          enable_jekyll: true
